name: "Test Pull Request"

on:  push

jobs:
  merge-pull-request:
   runs-on: ubuntu-latest

   
   steps:
     
    
   - name: Checkout repository
     uses: actions/checkout@v3
   - name: approve pull request
     uses: juliangruber/approve-pull-request-action@v1.1.1
     with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      number: 1
   
   - name: Merge Pull Request
     uses: juliangruber/merge-pull-request-action@v1
     with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      number: 1
      method: merge


 
